"""Rental comparable selection, rental estimate persistence, and the synthetic
rental corpus (Slice 3).

Geospatial work is done by PostGIS (ADR-002) with the same expanding-radius
strategy as the sale-comparable search, reusing its radius steps, lookback
window and area band so a rental estimate and a fair value are never drawn
from differently-shaped neighbourhoods.

IMPORTANT -- the corpus generated by `seed_rental_comparables` is SYNTHETIC.
It is deterministic fixture data registered under a source flagged
`is_synthetic=True` with a licence string that says so, exactly as the sale
corpus is, so that every yield derived from it is visibly labelled. Presenting
fabricated leases as real market rents is the failure this platform exists to
prevent.
"""

from __future__ import annotations

import hashlib
import json
import random
import uuid
from dataclasses import dataclass
from datetime import UTC, date, datetime, timedelta
from decimal import Decimal

from geoalchemy2 import Geography
from sqlalchemy import cast, func, select
from sqlalchemy.orm import Session

from sreoi_domain.cost import TrueAcquisitionCost
from sreoi_domain.rental import (
    DEFAULT_ASSUMPTIONS,
    MIN_RENTAL_COMPARABLES,
    InsufficientRentalEvidenceError,
    RentalAssumptions,
    RentalComparable,
    RentalEstimate,
    RentalYield,
    YieldRefused,
    compute_yield,
    estimate_rent,
)
from sreoi_domain.valuation import SubjectProperty
from sreoi_persistence.models import District, Opportunity, Property, Source, SourceRecord
from sreoi_persistence.models_rental import (
    RentalComparable as RentalComparableRow,
)
from sreoi_persistence.models_rental import (
    RentalEstimateComparable,
    RentalEstimateRow,
)
from sreoi_persistence.repositories import (
    AREA_LOWER_FACTOR,
    AREA_UPPER_FACTOR,
    LOOKBACK_MONTHS,
    RADIUS_STEPS_M,
)
from sreoi_sources.base import AvailabilityLabel, LegalAccessMethod

SYNTHETIC_RENTAL_SOURCE_KEY = "synthetic_rental_fixture"

# Plausible Riyadh apartment asking rents, SAR per m2 per year, used only to
# generate the synthetic corpus. Set against the sale price levels in
# `seed._BASE_PPSQM` so implied yields on market value land near 7%, matching
# the order of magnitude in the specification's worked example (spec section 6:
# SAR 61,000 a year on a 140 m2 Sidrah apartment). Numbers this fixture
# produces are fabricated and labelled as such; they are not a market
# observation, and no user-facing yield should rest on them.
_BASE_RENT_PER_SQM_YEAR = {
    "Qurtubah": 505.0,
    "Al Munsiyah": 440.0,
    "Al Rimal": 400.0,
    "Sidrah": 475.0,
}
_RENT_FLOOR_PER_SQM_YEAR = 350.0
_RENT_CEILING_PER_SQM_YEAR = 650.0


def _point(lon: float, lat: float) -> str:
    return f"SRID=4326;POINT({lon} {lat})"


@dataclass(frozen=True, slots=True)
class StoredRentalEstimate:
    """What the pipeline produced and wrote, returned so the caller can score."""

    row_id: uuid.UUID
    estimate: RentalEstimate
    rental_yield: RentalYield | YieldRefused
    radius_m: float

    @property
    def gross_yield(self) -> float | None:
        """The yield the score may use, or None when it was refused.

        None rather than 0.0: the scorer treats a missing yield as an absent
        dimension, whereas 0.0 would assert a fact we have not established.
        """
        return self.rental_yield.gross if isinstance(self.rental_yield, RentalYield) else None

    @property
    def net_yield(self) -> float | None:
        return self.rental_yield.net if isinstance(self.rental_yield, RentalYield) else None


class RentalComparableRepository:
    """Expanding-radius lease search.

    Lives here rather than in `sreoi_persistence.repositories` only because
    that module is shared with concurrent work in this slice; it belongs
    alongside `ComparableRepository` and should be moved there on integration.
    """

    def __init__(self, session: Session) -> None:
        self._session = session

    def find(
        self,
        *,
        longitude: float,
        latitude: float,
        property_class: str,
        area_sqm: float,
        as_of: date,
        min_comparables: int = MIN_RENTAL_COMPARABLES,
    ) -> tuple[list[RentalComparable], float]:
        """Returns the leases found and the radius that produced them.

        The radius is returned rather than discarded so the caller can record
        that the search had to reach beyond the immediate neighbourhood: a
        lease from further away is a weaker claim and the output must say so.
        """
        subject = cast(func.ST_SetSRID(func.ST_MakePoint(longitude, latitude), 4326), Geography)
        cutoff = as_of - timedelta(days=int(LOOKBACK_MONTHS * 30.44))

        found: list[RentalComparable] = []
        used_radius = RADIUS_STEPS_M[-1]

        for radius in RADIUS_STEPS_M:
            stmt = (
                select(
                    RentalComparableRow,
                    func.ST_Distance(RentalComparableRow.location, subject).label("distance_m"),
                )
                .where(
                    RentalComparableRow.property_class == property_class,
                    RentalComparableRow.contract_date >= cutoff,
                    RentalComparableRow.contract_date <= as_of,
                    RentalComparableRow.area_sqm >= area_sqm * AREA_LOWER_FACTOR,
                    RentalComparableRow.area_sqm <= area_sqm * AREA_UPPER_FACTOR,
                    func.ST_DWithin(RentalComparableRow.location, subject, radius),
                )
                .order_by("distance_m")
                .limit(200)
            )
            rows = self._session.execute(stmt).all()
            if len(rows) >= min_comparables or radius == RADIUS_STEPS_M[-1]:
                found = [
                    RentalComparable(
                        id=row.id,
                        annual_rent=Decimal(row.annual_rent),
                        area_sqm=float(row.area_sqm),
                        contract_date=row.contract_date,
                        distance_m=float(distance),
                        property_class=row.property_class,
                        district_id=row.district_id,
                        project_id=row.project_id,
                        build_year=row.build_year,
                        floor=row.floor,
                    )
                    for row, distance in rows
                ]
                used_radius = radius
                break

        return found, used_radius

    def count_since(
        self,
        *,
        longitude: float,
        latitude: float,
        property_class: str,
        area_sqm: float,
        since: datetime,
        radius_m: float = RADIUS_STEPS_M[-1],
    ) -> int:
        """Relevant leases ingested since an instant.

        Backs the alerting trigger "a new relevant comparable appeared": new
        evidence can move a valuation, and a user monitoring an area is
        entitled to know the evidence base changed under them.
        """
        subject = cast(func.ST_SetSRID(func.ST_MakePoint(longitude, latitude), 4326), Geography)
        return int(
            self._session.scalar(
                select(func.count())
                .select_from(RentalComparableRow)
                .where(
                    RentalComparableRow.property_class == property_class,
                    RentalComparableRow.area_sqm >= area_sqm * AREA_LOWER_FACTOR,
                    RentalComparableRow.area_sqm <= area_sqm * AREA_UPPER_FACTOR,
                    RentalComparableRow.ingested_at > since,
                    func.ST_DWithin(RentalComparableRow.location, subject, radius_m),
                )
            )
            or 0
        )


def ensure_rental_source(session: Session) -> Source:
    """Get or create the synthetic rental source, labelled as synthetic."""
    source = session.scalar(select(Source).where(Source.key == SYNTHETIC_RENTAL_SOURCE_KEY))
    if source is not None:
        return source
    source = Source(
        key=SYNTHETIC_RENTAL_SOURCE_KEY,
        name="Synthetic rental comparable corpus (DEMONSTRATION DATA)",
        legal_access_method=LegalAccessMethod.MANUAL_UPLOAD.value,
        data_license=(
            "SYNTHETIC - generated fixture, NOT real lease or Ejar contract data. "
            "Replaced by a licensed rental-contract feed before any yield is "
            "presented to a user as market evidence."
        ),
        availability_label=AvailabilityLabel.CONFIRMED.value,
        source_confidence=0.35,
        is_synthetic=True,
    )
    session.add(source)
    session.flush()
    return source


def seed_rental_comparables(
    session: Session,
    *,
    per_district: int = 40,
    seed: int = 20260903,
) -> int:
    """Generate a deterministic SYNTHETIC rental corpus for the four districts.

    Idempotent: does nothing when the synthetic source already has leases.
    """
    # Imported here, not at module scope: `seed` pulls in the KAPSARC HTTP
    # connector, and the evaluation path (which imports this module) should not
    # drag a network client in behind it.
    from sreoi_pipeline.seed import RIYADH_DISTRICTS

    source = ensure_rental_source(session)
    existing = session.scalar(
        select(func.count())
        .select_from(RentalComparableRow)
        .where(RentalComparableRow.source_id == source.id)
    )
    if existing:
        return 0

    # The generated corpus is itself a source record, so its provenance and
    # freshness appear on the admin dashboard like any other source.
    manifest = {
        "generator": "seed_rental_comparables",
        "seed": seed,
        "per_district": per_district,
        "districts": [name for name, *_ in RIYADH_DISTRICTS],
        "unit": "SAR per m2 per year",
        "synthetic": True,
    }
    digest = hashlib.sha256(json.dumps(manifest, sort_keys=True).encode()).hexdigest()
    if not session.scalar(
        select(SourceRecord).where(
            SourceRecord.source_id == source.id, SourceRecord.content_hash == digest
        )
    ):
        session.add(
            SourceRecord(
                source_id=source.id,
                external_id=f"synthetic-rental-corpus-{seed}",
                content_hash=digest,
                raw_payload=manifest,
            )
        )
        session.flush()

    rng = random.Random(seed)
    today = date.today()
    count = 0

    for name_en, _name_ar, lon, lat, _liquidity, _location in RIYADH_DISTRICTS:
        district = session.scalar(select(District).where(District.name_en == name_en))
        if district is None:
            continue
        base = _BASE_RENT_PER_SQM_YEAR[name_en]
        for _ in range(per_district):
            days_ago = rng.randint(15, 690)
            signed = today - timedelta(days=days_ago)
            # Gentle upward drift plus dispersion, then clamped to the
            # plausible band so the fixture never claims an absurd rent.
            drift = 1.0 - (days_ago / 365.0) * 0.035
            ppsqm = base * drift * rng.gauss(1.0, 0.08)
            ppsqm = min(_RENT_CEILING_PER_SQM_YEAR, max(_RENT_FLOOR_PER_SQM_YEAR, ppsqm))
            area = round(rng.uniform(95, 210), 1)
            offset = 0.014
            session.add(
                RentalComparableRow(
                    source_id=source.id,
                    district_id=district.id,
                    location=_point(
                        lon + rng.uniform(-offset, offset), lat + rng.uniform(-offset, offset)
                    ),
                    annual_rent=Decimal(str(round(ppsqm * area, 2))),
                    area_sqm=area,
                    contract_date=signed,
                    property_class="APARTMENT",
                    build_year=rng.randint(2012, 2024),
                    floor=rng.randint(1, 12),
                    ingested_at=datetime.now(UTC),
                )
            )
            count += 1
    session.flush()
    return count


def estimate_and_store_rent(
    session: Session,
    opportunity: Opportunity,
    *,
    as_of: date,
    longitude: float,
    latitude: float,
    cost: TrueAcquisitionCost,
    subject_completeness: float = 1.0,
    assumptions: RentalAssumptions = DEFAULT_ASSUMPTIONS,
) -> StoredRentalEstimate | None:
    """Estimate rent for one opportunity, compute the yield, and persist both.

    Returns None when rental evidence is too thin. Nothing is written in that
    case and the caller passes `gross_yield=None` to the scorer, so a property
    with no lease evidence is not scored as though it had a zero yield -- it is
    scored as one whose rental dimension is unestablished.
    """
    prop: Property = opportunity.property
    subject = SubjectProperty(
        property_class=prop.property_class,
        area_sqm=float(prop.built_area_sqm),
        district_id=prop.district_id,
        project_id=prop.project_id,
        build_year=prop.build_year,
        floor=prop.floor,
    )

    comps, radius_used = RentalComparableRepository(session).find(
        longitude=longitude,
        latitude=latitude,
        property_class=prop.property_class,
        area_sqm=subject.area_sqm,
        as_of=as_of,
    )

    try:
        estimate = estimate_rent(
            subject, comps, as_of=as_of, subject_completeness=subject_completeness
        )
    except InsufficientRentalEvidenceError:
        return None

    rental_yield = compute_yield(
        annual_rent=estimate.annual_rent,
        true_acquisition_cost=cost.total,
        cost_is_complete=cost.is_complete,
        assumptions=assumptions,
    )

    row = RentalEstimateRow(
        opportunity_id=opportunity.id,
        property_id=prop.id,
        annual_rent=estimate.annual_rent,
        annual_rent_low=estimate.annual_rent_low,
        annual_rent_high=estimate.annual_rent_high,
        rent_per_sqm_year=estimate.rent_per_sqm_year,
        comparable_count=estimate.comparable_count,
        effective_n=estimate.effective_n,
        comparable_quality=estimate.comparable_quality,
        confidence=estimate.confidence,
        gross_yield=rental_yield.gross if isinstance(rental_yield, RentalYield) else None,
        net_yield=rental_yield.net if isinstance(rental_yield, RentalYield) else None,
        yield_refused_reason=(
            rental_yield.reason if isinstance(rental_yield, YieldRefused) else None
        ),
        opex_total=(rental_yield.opex_total if isinstance(rental_yield, RentalYield) else None),
        # Written with the numbers, not read from configuration at display
        # time, so a stored yield stays reproducible after a default changes.
        assumptions={
            **assumptions.describe(),
            "search_radius_m": radius_used,
            "monthly_rent": float(estimate.monthly_rent),
            "opex_breakdown": (
                rental_yield.opex_breakdown if isinstance(rental_yield, RentalYield) else None
            ),
        },
        method_version=estimate.method_version,
    )
    session.add(row)
    session.flush()

    for wc in estimate.comparables:
        session.add(
            RentalEstimateComparable(
                rental_estimate_id=row.id,
                rental_comparable_id=wc.comparable.id,
                weight=round(wc.weight, 5),
                distance_m=wc.comparable.distance_m,
                rent_per_sqm_year=wc.rent_per_sqm_year,
                weight_breakdown={k: round(v, 5) for k, v in wc.weight_breakdown.items()},
                excluded_reason=wc.excluded_reason,
            )
        )

    return StoredRentalEstimate(
        row_id=row.id, estimate=estimate, rental_yield=rental_yield, radius_m=radius_used
    )
